<?php
//khai báo 1 class ConNguoi bao gồm các thuộc tính sau :
//hoten,namsinh,diachi,sodienthoai,email
//định nghĩa phương thức tính tuổi trong class tuổi = năm hiện tại - năm sinh
//tạo class SinhVien kế thừa từ class ConNguoi và class SinhVien có thuộc tính
//diemtoan,diemly,diemhoa
//có phương thức tính điểm TB = (toán + lý + hóa)/3
//tạo phương thức hiển thị thông tin sinh viên gồm hoten-sodienthoai-tuổi-điểmTB
//tạo class GiangVien kế thừa từ class ConNguoi có thuộc tính lương cơ bản,số giờ dạy
//tạo phương thức tính tổng lương = lương cơ bản * số giờ dạy
//tạo phương thức hiển thị thông tin giảng viên gồm hoten-sodienthoai-tuổi-Tổng lương

class ConNguoi{
    public $hoTen;
    public $namSinh;
    public $diaChi;
    public $soDienThoai;
    public $email;

    public function __construct($hoTen,$namSinh,$diaChi,$soDienThoai,$email)
    {
        $this->hoTen=$hoTen;
        $this->namSinh=$namSinh;
        $this->diaChi=$diaChi;
        $this->soDienThoai=$soDienThoai;
        $this->email=$email;

    }
    public function tinhTuoi(){
        return date("Y")-$this->namSinh;
    }
    public function hienThi(){

        echo "Họ và tên: ".$this->hoTen;
        echo "<br>";
        echo "Số điện thoại: ".$this->soDienThoai;
        echo "<br>";
        echo "Tuổi: ".$this->tinhTuoi();
    }

}

class SinhVien extends ConNguoi{
    public $diemToan;
    public $diemLy;
    public $diemHoa;

    public function __construct($hoTen,$namSinh,$diaChi,$soDienThoai,$email,$diemToan,$diemLy,$diemHoa)
    {
        parent::__construct($hoTen,$namSinh,$diaChi,$soDienThoai,$email);
        $this->diemToan=$diemToan;
        $this->diemLy=$diemLy;
        $this->diemHoa=$diemHoa;
    }
    public function diemTB(){
        return ($this->diemToan+$this->diemLy+$this->diemHoa)/3;
    }

    public function hienThi()
    {
        echo "<p style='color: red'>Thông tin sinh viên</p>";
        parent::hienThi(); // TODO: Change the autogenerated stub
        echo "<br>";
        echo "Điểm TB: ".$this->diemTB();
    }
}

class GiangVien extends ConNguoi {
    public $luongCB;
    public $soGioDay;
        public function __construct($hoTen, $namSinh, $diaChi, $soDienThoai, $email,$luongCB,$soGioDay)
        {
            parent::__construct($hoTen, $namSinh, $diaChi, $soDienThoai, $email);
            $this->luongCB=$luongCB;
            $this->soGioDay=$soGioDay;
        }
        public function tinhLuong(){
        return $this->luongCB*$this->soGioDay;
        }
        public function hienThi()
        {
            echo "<p style='color: red'>Thông tin giảng viên</p>";

            parent::hienThi(); // TODO: Change the autogenerated stub
            echo "<br>";
            echo "Tổng lương: ".$this->tinhLuong();
        }
}
$sv=new SinhVien("Thuỷ",2003,"HN",98866776,"thuyfpt",9,8,8);
$sv->hienThi();

$gv=new GiangVien("Thắng",1996,"HP",98877783,"thàngpt@fpt",2000,2);
$gv->hienThi();